modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
[[mods]] #mandatory
modId="essence" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Essence" #mandatory
logoFile="logo.png" #optional
credits="benbenlaw" #optional
authors="benbenlaw" #optional
description='''
A mod about essences
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.essence]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[38,)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="BOTH"
# Here's another dependency
[[dependencies.essence]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.18,1.19)"
   ordering="NONE"
   side="BOTH"
[[dependencies.essence]]
   modId="custommachinery"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[0,)"
   ordering="NONE"
   side="BOTH"



